services:
  db:
    image: mysql:8.0
    restart: always
    command: --default-authentication-plugin=mysql_native_password --sql-mode=""
    environment:
      MYSQL_DATABASE: 'db_bof'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - bof-db:/var/lib/mysql
# Names our volume
volumes:
  bof-db:
