export const projectCredits = {
    title: 'INFINIX HOT 12',
    subtitle: 'Digital Video Commercial | 15 Seconds | Color | 16:9',
    description:
        'Dominasi game dan tampil jadi juara dengan Infinix HOT 12 yang dilengkapi prosesor gaming Helio G85 untuk performa main makin ganas!',
    credits: [
        { role: 'Year', names: ['2022'] },
        { role: 'Client', names: ['INFINIX INDONESIA'] },
        { role: 'Agency', names: ['HATMA Creative'] },
        { role: 'Executive Producer', names: ['Fersya Adam'] },
        { role: 'Producer', names: ['Aditya Alfiqry'] },
        { role: 'Director', names: ['Wahyu Gunawan'] },
        { role: 'Astrada', names: ['Eliseya Trifora'] },
        { role: 'Clapper', names: ['Naditya'] },
        { role: 'Production Assistant', names: ['Agnes Elika'] },
        { role: 'Line Production', names: ['Allya Nissa'] },
        { role: 'Director of Photography', names: ['Randy Azhari'] },
        { role: 'Assistant Camera', names: ['Rasyadan Muhammad'] },
        { role: 'Gaffer', names: ['Derry Januar'] },
        { role: 'Best boy', names: ['Rangga', 'Ridho'] },
        { role: 'DIT', names: ['Willy Marthen'] },
        { role: 'Cinelog', names: ['Eko Prasetiyo'] },
        { role: 'Art Director', names: ['Djati Hendrianto'] },
        { role: 'Assistant Art Dir', names: ['Yasin Habibie'] },
        { role: 'Prop Master', names: ['Reynaldi Akbar'] },
        { role: 'Dresser', names: ['Enrico Gautama', 'Irfan Cahya'] },
        { role: 'Standby set', names: ['Kurniawan Awe'] },
        { role: 'Build', names: ['Indra Gembong'] },
        { role: 'Storyboard', names: ['Eko Nurcahyo'] },
        { role: 'Wardrobe', names: ['Irani Richa'] },
        { role: 'Make up', names: ['Salsabil Jawahir'] },
        { role: 'Casting Director', names: ['Maya Wulandari'] },
        { role: 'Talent Koordinator', names: ['Cut Qitha'] },
        { role: 'Editor offline', names: ['Khairun Naim'] },
        { role: 'Editor online', names: ['Malik Stanser'] },
        { role: 'Colorists', names: ['Yehuda Aribowo'] },
        { role: 'Audio Post', names: ['MIXTAPE Audio Works'] },
        { role: 'Sound Designer', names: ['Wiansa Dewata'] },
        { role: 'Producer Audio Post', names: ['Danaci Manalu'] },
        { role: 'Re-recording mixer', names: ['Hangga Patty'] },
        { role: 'Voice Over Artist', names: ['Johnny White'] },
        { role: 'Behind The Scene', names: ['Gatot Jalu'] },
    ],
};
